# Spam classification 


In [3]:
import numpy as np
import pandas as pd

In [5]:
data1 = pd.read_csv("comm-psy.csv")

In [6]:
data1

COMMENT_ID  \
0    LZQPQhLyRh80UYxNuaDWhIGQYNQ96IuCg-AYWqNPjpU   
1    LZQPQhLyRh_C2cTtd9MvFRJedxydaVW-2sNg5Diuo4A   
2    LZQPQhLyRh9MSZYnf8djyk0gEF9BHDPYrrK-qCczIY8   
3            z13jhp0bxqncu512g22wvzkasxmvvzjaz04   
4            z13fwbwp1oujthgqj04chlngpvzmtt3r3dw   
..                                           ...   
345            z13th1q4yzihf1bll23qxzpjeujterydj   
346        z13fcn1wfpb5e51xe04chdxakpzgchyaxzo0k   
347          z130zd5b3titudkoe04ccbeohojxuzppvbg   
348          z12he50arvrkivl5u04cctawgxzkjfsjcc4   
349        z13vhvu54u3ewpp5h04ccb4zuoardrmjlyk0k   

                                   AUTHOR                 DATE  \
0                               Julius NM  2013-11-07T06:20:48   
1                             adam riyati  2013-11-07T12:37:15   
2                        Evgeny Murashkin  2013-11-08T17:34:21   
3                         ElNino Melendez  2013-11-09T08:28:43   
4                                  GsMega  2013-11-10T16:05:38   
..                                    ...                  ...   
345                       Carmen Racasanu  2014-11-14T13:27:52   
346                       diego mogrovejo  2014-11-14T13:28:08   
347  BlueYetiPlayz -Call Of Duty and More  2015-05-23T13:04:32   
348                          Photo Editor  2015-06-05T14:14:48   
349                            Ray Benich  2015-06-05T18:05:16   

                                               CONTENT  CLASS  
0    Huh, anyway check out this you[tube] channel: ...      1  
1    Hey guys check out my new channel and our firs...      1  
2               just for test I have to say murdev.com      1  
3     me shaking my sexy ass on my channel enjoy ^_^       1  
4              watch?v=vtaRGgvGtWQ   Check this out .      1  
..                                                 ...    ...  
345  How can this have 2 billion views when there's...      0  
346         I don't now why I'm watching this in 2014      0  
347  subscribe to me for call of duty vids and give...      1  
348  hi guys please my android photo editor downloa...      1  
349  The first billion viewed this because they tho...      0  

[350 rows x 5 columns]

In [5]:
data2 = pd.read_csv("comm-katyperry.csv")

In [6]:
data2

COMMENT_ID               AUTHOR  \
0        z12pgdhovmrktzm3i23es5d5junftft3f          lekanaVEVO1   
1      z13yx345uxepetggz04ci5rjcxeohzlrtf4             Pyunghee   
2    z12lsjvi3wa5x1vwh04cibeaqnzrevxajw00k           Erica Ross   
3      z13jcjuovxbwfr0ge04cev2ipsjdfdurwck         Aviel Haimov   
4    z13qybua2yfydzxzj04cgfpqdt2syfx53ms0k           John Bello   
..                                     ...                  ...   
345    z12sjp3zgtqnvlysj23zuxxaolrvd1oj504          Kacy Cluley   
346  z132enrpoy35yxpoe04cjr4zur3jvbyq3xo0k    Kasia Fabisiewicz   
347      z132jbmxfqm4fjysg23nwjfb2mv2vxnua  Decio Alves Martins   
348    z12cdlswetvnejcri04cex0jfwy2u3tzj54         Rafi Hossain   
349  z120e5uautvcuper304ccf4bjrjugdpbwrc0k           moaz adnan   

                    DATE                                            CONTENT  \
0    2014-07-22T15:27:50  i love this so much. AND also I Generate Free ...   
1    2014-07-27T01:57:16  http://www.billboard.com/articles/columns/pop-...   
2    2014-07-27T02:51:43  Hey guys! Please join me in my fight to help a...   
3    2014-08-01T12:27:48  http://psnboss.com/?ref=2tGgp3pV6L this is the...   
4    2014-08-01T21:04:03  Hey everyone. Watch this trailer!!!!!!!!  http...   
..                   ...                                                ...   
345  2015-06-05T18:59:52  This song means so much to me thank you  soooo...   
346  2015-06-05T19:02:05                                             &lt;3   
347  2015-06-05T19:29:20  KATY PERRY, I AM THE "DÉCIO CABELO", "DECIO HA...   
348  2015-06-05T19:55:08  Honestly speaking except taylor swift and adel...   
349  2015-06-05T20:01:23  who is going to reach the billion first : katy...   

     CLASS  
0        1  
1        1  
2        1  
3        1  
4        1  
..     ...  
345      0  
346      0  
347      1  
348      0  
349      0  

[350 rows x 5 columns]

In [7]:
data3 = pd.read_csv("comm-lmfao.csv")

In [8]:
data4 = pd.read_csv("comm-eminem.csv")

In [9]:
data5 = pd.read_csv("comm-shakira.csv")

In [10]:
li = []
for data in (data1, data2, data3, data4, data5):
    li.append(data)
df_all = pd.concat(li, axis=0, ignore_index=True)

In [355]:
df = pd.read_csv("comments.csv")

In [357]:
df

CONTENT  CLASS
0     Huh, anyway check out this you[tube] channel: ...      1
1     Hey guys check out my new channel and our firs...      1
2                just for test I have to say murdev.com      1
3      me shaking my sexy ass on my channel enjoy ^_^       1
4               watch?v=vtaRGgvGtWQ   Check this out .      1
...                                                 ...    ...
2088  Follow me for fashion inspiration and the late...      1
2089  Win a photoshoot! Follow and like to enter the...      1
2090  Get 1000 followers instantly! Limited spots av...      1
2091  Follow and like for a chance to win a brand ne...      1
2092  Join my engagement pod! Boost your engagement ...      1

[2093 rows x 2 columns]

In [361]:
words = pd.read_csv("words.csv")

In [362]:
words

Rank          Word Part of speech  Frequency Dispersion
0        1           the              a   22038615       0,98
1        2            be              v   12545825       0,97
2        3           and              c   10741073       0,99
3        4            of              i   10343885       0,97
4        5             a              a   10144200       0,98
...    ...           ...            ...        ...        ...
4995  4996     plaintiff              n       5312       0,88
4996  4997           kid              v       5094       0,92
4997  4998  middle-class              j       5025       0,93
4998  4999       apology              n       4972       0,94
4999  5000          till              i       5079       0,92

[5000 rows x 5 columns]

In [363]:
words = words["Word"].squeeze()

In [364]:
words

0                the
1                 be
2                and
3                 of
4                  a
            ...     
4995       plaintiff
4996             kid
4997    middle-class
4998         apology
4999            till
Name: Word, Length: 5000, dtype: object

In [365]:
#new_symbols = [",",".","!","@","#","$","%","^","&","*","(",")","-","+","_","=",":",";","?","/","\\"]
new_symbols = [",", ".", "!", "@", "#", "$", "%", "^", "&", "*", "(", ")", "-", "+", "_", "=", ":", ";", "?", "/", "\\", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "😊", "😂", "😍", "👍", "🔥", "💯", "🎉", "❤️", "😎", "🙌", "👏", "✨", "🚀", "🌟", "💥", "🎊", "💪"]


In [366]:
words = pd.concat([words, pd.Series(new_symbols)])

In [367]:
# Re-indexing the Series to have a sequential index starting from 0

words.reset_index(drop=True, inplace=True)

In [397]:
words.to_csv("words_list.csv", index=False)

In [442]:
words = pd.read_csv("words_list.csv")
words = words["0"]
words

0       the
1        be
2       and
3        of
4         a
       ... 
5043      🚀
5044      🌟
5045      💥
5046      🎊
5047      💪
Name: 0, Length: 5048, dtype: object

In [455]:
def message_to_words(message):
    """
    The function message_to_words(message) only accepts a string as input. 
    It splits the input string into individual words, 
    converts each word to lowercase, and returns a list of these lowercase words.
    """
    words_ = []
    for word in message.split(" "):
        words_.append(word.lower())
    return words_

In [457]:
def make_rows(messages, words=words):
    """
    The make_rows(messages, words=words) function exclusively accepts a list as its input.
    It dissects each message within the list into individual words and generates a list of dictionaries. 
    These dictionaries depict messages and detail the presence of each word from a specified word list.
    """
    result = []
    symbols_to_check = set(".,!@#$%^&*()-+_=:;?/\\1234567890><😊😂😍👍🔥💯🎉❤️😎🙌👏✨🚀🌟💥🎊💪")
    symbols_to_check_map = ".,!@#$%^&*()-+_=:;?/\\1234567890><😊😂😍👍🔥💯🎉❤️😎🙌👏✨🚀🌟💥🎊💪"
    translation_map = str.maketrans('', '', symbols_to_check_map)
    for message in messages:
        word_dict = {}
        for word in words:
            if word in message:
                word_dict[word] = 1
            else:
                for x in message:
                    for letter in x:
                        if letter in symbols_to_check:
                            word_dict[letter] = 1
                    new_word = x.translate(translation_map)
                    if new_word in words:
                        word_dict[new_word] = 1
                word_dict[word] = 0
        result.append(word_dict)
    return result

In [390]:
messages = [message_to_words(message) for message in list(df.CONTENT)]

In [393]:
rows = make_rows(messages)

In [394]:
df_final = pd.DataFrame(rows, columns=words)

In [395]:
df_final["target_"] = df.CLASS

In [403]:
df_final.to_csv("comments_data.csv", index=False)

In [404]:
df_final

the  be  and  of  a  in  to  have  to  it  ...  😎  🙌  👏  ✨  🚀  🌟  💥  🎊  \
0       0   0    0   0  0   0   0     0   0   0  ...  0  0  0  0  0  0  0  0   
1       1   0    1   0  1   1   0     0   0   0  ...  0  0  0  0  0  0  0  0   
2       0   0    0   0  0   0   1     1   1   0  ...  0  0  0  0  0  0  0  0   
3       0   0    0   0  0   0   0     0   0   0  ...  0  0  0  0  0  0  0  0   
4       0   0    0   0  0   0   0     0   0   0  ...  0  0  0  0  0  0  0  0   
...   ...  ..  ...  .. ..  ..  ..   ...  ..  ..  ... .. .. .. .. .. .. .. ..   
2088    1   0    1   0  0   0   0     0   0   0  ...  0  0  0  0  0  0  0  0   
2089    1   0    1   0  1   0   1     0   1   0  ...  0  0  0  0  0  0  0  0   
2090    0   0    0   0  0   0   0     0   0   0  ...  0  0  0  0  0  0  0  0   
2091    0   0    1   0  1   0   1     0   1   0  ...  0  0  0  0  0  0  0  0   
2092    0   0    1   0  0   0   0     0   0   0  ...  0  0  0  0  0  0  0  0   

      💪  target_  
0     0        1  
1     0        1  
2     0        1  
3     0        1  
4     0        1  
...  ..      ...  
2088  0        1  
2089  0        1  
2090  0        1  
2091  0        1  
2092  0        1  

[2093 rows x 5049 columns]

In [405]:
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import precision_score, recall_score, f1_score
from sklearn.metrics import RocCurveDisplay


X = df_final.drop("target_", axis=1)
y = df_final["target_"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [406]:
models = {"Logistic Regression": LogisticRegression(),
          "KNN": KNeighborsClassifier(),
          "Random Forest": RandomForestClassifier(),
          "SVC": SVC(),
         "LinearSVC": LinearSVC(dual="auto")}

def fit_and_score(models, X_train, X_test, y_train, y_test):
    np.random.seed(42)
    model_scores = {}
    for name, model in models.items():
        model.fit(X_train, y_train)
        model_scores[name] = model.score(X_test, y_test)
    return model_scores

In [407]:
fit_and_score(models, X_train, X_test, y_train, y_test)

{'Logistic Regression': 0.918854415274463,
 'KNN': 0.8568019093078759,
 'Random Forest': 0.9260143198090692,
 'SVC': 0.9307875894988067,
 'LinearSVC': 0.9045346062052506}

In [141]:

np.random.seed(42)
svc_grid = {"C": np.logspace(-4, 4, 20),
           "kernel": ["sigmoid", "linear", "rbf", "poly"],
           'gamma': [1, 0.7, 0.1, 0.0001]}

rf_grid = {"n_estimators": [100,150,200],
           "max_depth": [None, 3, 5, 10],
           "min_samples_split": np.arange(2, 20, 2),
           "min_samples_leaf": np.arange(1, 20, 2)}   

rs_svc = RandomizedSearchCV(SVC(), svc_grid, cv=3, verbose=True, n_iter=200, n_jobs=-1)
rs_svc.fit(X_train, y_train)

C:\Users\mrinc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_search.py:307: UserWarning: The total space of parameters 36 is smaller than n_iter=200. Running 36 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(


Fitting 3 folds for each of 36 candidates, totalling 108 fits


RandomizedSearchCV(cv=3, estimator=SVC(), n_iter=200, n_jobs=-1,
                   param_distributions={'C': array([1.e-04, 1.e+00, 1.e+04]),
                                        'gamma': [1, 0.1, 0.0001],
                                        'kernel': ['sigmoid', 'linear', 'rbf',
                                                   'poly']},
                   verbose=True)

In [221]:
rs_svc.best_params_

{'kernel': 'rbf', 'gamma': 0.1, 'C': 1.0}

In [409]:
model = SVC(kernel="rbf", gamma=0.1, C=1.0, random_state=42)
model.fit(X_train, y_train)
model.score(X_test, y_test)

0.9331742243436754

In [410]:
preds = model.predict(X_test)

In [411]:
recall_score(y_test, preds), precision_score(y_test, preds), f1_score(y_test, preds), model.score(X_test, y_test)

(0.9227272727272727,
 0.9485981308411215,
 0.9354838709677419,
 0.9331742243436754)

In [196]:
0.95833 gamma=0.5

SyntaxError: invalid syntax (2932206639.py, line 1)

In [412]:
confusion_matrix(y_test, preds)

array([[188,  11],
       [ 17, 203]], dtype=int64)

In [413]:
print(classification_report(y_test, preds))

              precision    recall  f1-score   support

           0       0.92      0.94      0.93       199
           1       0.95      0.92      0.94       220

    accuracy                           0.93       419
   macro avg       0.93      0.93      0.93       419
weighted avg       0.93      0.93      0.93       419


In [414]:
df_final["target_"].sum()

1142

In [464]:
def is_spam(message, model=model):
    """
    Predicts whether a given message or list of messages is spam or not.

    Parameters:
    - message (str or list of str): The message or list of messages to be classified. If a single message is provided,
      it should be a string. If multiple messages are provided, they should be contained within a list of strings.

    Returns:
    - pred (array-like): An array-like object containing the predicted labels for each input message. A value of 1
      indicates that the message is classified as spam, while a value of 0 indicates that the message is not spam.
    """
    if isinstance(message, list):
        words_ = [message_to_words(message_) for message_ in message]
    elif isinstance(message, str):
        words_ = [message_to_words(message)]
    else:
        print("The provided data is in the wrong format. Please provide the data in the format of a list or a string.")
    rows = make_rows(words_)
    df_test = pd.DataFrame(rows, columns=words)
    df_test = df_test.dropna()
    pred = model.predict(df_test)
    return pred

In [459]:
comments = [
    "Beautiful photo! 😍",
    "Great content as always!",
    "Love your style! 💖",
    "Amazing shot! 📸",
    "Nice feed! Keep it up!",
    "This is so cool! 😎",
    "You're so talented!",
    "Awesome post!",
    "I admire your work!",
    "Fantastic picture! 👌",
    "Check out my profile for amazing deals!",
    "Get free followers now! Click the link in bio!",
    "Want to be Instagram famous? Follow me!",
    "Buy followers and likes! Best prices here!",
    "I make $1000 a day on Instagram! Ask me how!",
    "Get rich quick! Follow my strategy!",
    "Want to grow your account? DM me!",
    "Limited time offer! Follow for discounts!",
    "Boost your engagement! Follow for tips!",
    "Get verified on Instagram! DM me for details!",
]
results = is_spam(comments)

In [460]:
results

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1],
      dtype=int64)

In [461]:
is_spam("🚨🚨🚨 ATTENTION ALL INSTAGRAM USERS 🚨🚨🚨 Want to make $1000 a day from home? 💰💰💰 Click the link in my bio NOW to join our exclusive money-making club! 💵💵💵 Don't miss out on this amazing opportunity! 🔥🔥🔥 #makemoneyonline #financialfreedom #getrichquick")

array([1], dtype=int64)

In [462]:
is_spam("Absolutely stunning capture! 😍 The colors in this photo are so vibrant, it's like a work of art. Makes me miss our adventures together!")

array([0], dtype=int64)

In [453]:
import pickle

with open('your_model.pkl', 'wb') as f:
    pickle.dump(model, f)


In [454]:
with open('your_model.pkl', 'rb') as f:
    loaded_model = pickle.load(f)

In [473]:
is_spam("This photo is beautiful. Where was it taken? I'm curious to know!", model=loaded_model)

array([0], dtype=int64)